### ISSUE TITLE
Running on Linux

### ISSUE THREAD

**Issue by LorenDB** [pmahend1/BingRewards#3]
I can't get this script running on Linux. Could you help me?

**Comment by pmahend1** [comment]
Did you build  project on Linux with .Net Core and have the Firefox browser?

**Comment by LorenDB** [comment]
I was trying to run the Python script.

**Comment by pmahend1** [comment]
Try .Net core if you have the SDK. whats the error are you getting.?

**Comment by LorenDB** [comment]
I'm using Python 2.7, although I could go to 3.7. I'm getting an error when I try to run the script because it's trying to run 'gecko.exe'.

**Comment by pmahend1** [comment]
You need python 3 for this. Python 2 is not supported.

**Comment by LorenDB** [comment]
OK. What about the 'gecko.exe' part?

**Comment by pmahend1** [comment]
You need to download [Linux release from here](https://github.com/mozilla/geckodriver/releases/tag/v0.26.0) Please provide me more details to investigate. Error message.

**Comment by LorenDB** [comment]
OK I believe I have got it working now. Thanks for your help.

**Comment by LorenDB** [comment]
Actually I have one error yet. I noticed this text when I run the script: Message: Unable to locate element: [name="loginfmt"]
What can be done to fix this?

**Comment by pmahend1** [comment]
Which browser is that?

**Comment by LorenDB** [comment]
It is from the Firefox browser.

**Comment by LorenDB** [comment]
It seems to me that the script is not actually sending variables to the Microsoft login page. I can't find anywhere that it actually defines a variable as being login.live.com.

**Comment by pmahend1** [comment]
yes..I am fixing it now.

**Comment by LorenDB** [comment]
Well, actually I just learned that technically this sort of thing is against the Microsoft Rewards terms of service, so I'm giving up this idea, but thanks for your help anyway.
